from enum import Enum

class HttpStatusCodes(Enum):
    HTTP_100_CONTINUE = 100
    HTTP_101_SWITCHING_PROTOCOLS = 101

    HTTP_200_OK = 200
    HTTP_201_CREATED = 201
    HTTP_202_ACCEPTED = 202
    HTTP_203_NON_AUTHORITATIVE_INFORMATION = 203
    HTTP_204_NO_CONTENT = 204
    HTTP_205_RESET_CONTENT = 205
    HTTP_206_PARTIAL_CONTENT = 206
    HTTP_207_MULTI_STATUS = 207
    HTTP_208_ALREADY_REPORTED = 208
    HTTP_226_IM_USED = 226

    HTTP_300_MULTIPLE_CHOICES = 300
    HTTP_301_MOVED_PERMANENTLY = 301
    HTTP_302_FOUND = 302
    HTTP_303_SEE_OTHER = 303
    HTTP_304_NOT_MODIFIED = 304
    HTTP_305_USE_PROXY = 305
    HTTP_306_RESERVED = 306
    HTTP_307_TEMPORARY_REDIRECT = 307
    HTTP_308_PERMANENT_REDIRECT = 308

    HTTP_400_BAD_REQUEST = 400
    HTTP_401_UNAUTHORIZED = 401
    HTTP_402_PAYMENT_REQUIRED = 402
    HTTP_403_FORBIDDEN = 403
    HTTP_404_NOT_FOUND = 404
    HTTP_405_METHOD_NOT_ALLOWED = 405
    HTTP_406_NOT_ACCEPTABLE = 406
    HTTP_407_PROXY_AUTHENTICATION_REQUIRED = 407
    HTTP_408_REQUEST_TIMEOUT = 408
    HTTP_409_CONFLICT = 409
    HTTP_410_GONE = 410
    HTTP_411_LENGTH_REQUIRED = 411
    HTTP_412_PRECONDITION_FAILED = 412
    HTTP_413_REQUEST_ENTITY_TOO_LARGE = 413
    HTTP_414_REQUEST_URI_TOO_LONG = 414
    HTTP_415_UNSUPPORTED_MEDIA_TYPE = 415
    HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE = 416
    HTTP_417_EXPECTATION_FAILED = 417
    HTTP_422_UNPROCESSABLE_ENTITY = 422
    HTTP_423_LOCKED = 423
    HTTP_424_FAILED_DEPENDENCY = 424
    HTTP_426_UPGRADE_REQUIRED = 426
    HTTP_428_PRECONDITION_REQUIRED = 428
    HTTP_429_TOO_MANY_REQUESTS = 429
    HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE = 431
    HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS = 451

    HTTP_500_INTERNAL_SERVER_ERROR = 500
    HTTP_501_NOT_IMPLEMENTED = 501
    HTTP_502_BAD_GATEWAY = 502
    HTTP_503_SERVICE_UNAVAILABLE = 503
    HTTP_504_GATEWAY_TIMEOUT = 504
    HTTP_505_HTTP_VERSION_NOT_SUPPORTED = 505
    HTTP_506_VARIANT_ALSO_NEGOTIATES = 506
    HTTP_507_INSUFFICIENT_STORAGE = 507
    HTTP_508_LOOP_DETECTED = 508
    HTTP_509_BANDWIDTH_LIMIT_EXCEEDED = 509
    HTTP_510_NOT_EXTENDED = 510
    HTTP_511_NETWORK_AUTHENTICATION_REQUIRED = 511


CLIENT_ERRORS_DICT = {
    HttpStatusCodes.HTTP_400_BAD_REQUEST.value: { 'message': 'BAD_REQUEST' },
    HttpStatusCodes.HTTP_401_UNAUTHORIZED.value: { 'message': 'UNAUTHORIZED' },
    HttpStatusCodes.HTTP_402_PAYMENT_REQUIRED.value: { 'message': 'PAYMENT_REQUIRED' },
    HttpStatusCodes.HTTP_403_FORBIDDEN.value: { 'message': 'FORBIDDEN' },
    HttpStatusCodes.HTTP_404_NOT_FOUND.value: { 'message': 'NOT_FOUND' },
    HttpStatusCodes.HTTP_405_METHOD_NOT_ALLOWED.value: { 'message': 'METHOD_NOT_ALLOWED' },
    HttpStatusCodes.HTTP_406_NOT_ACCEPTABLE.value: { 'message': 'NOT_ACCEPTABLE' },
    HttpStatusCodes.HTTP_407_PROXY_AUTHENTICATION_REQUIRED.value: { 'message': 'PROXY_AUTHENTICATION_REQUIRED' },
    HttpStatusCodes.HTTP_408_REQUEST_TIMEOUT.value: { 'message': 'REQUEST_TIMEOUT' },
    HttpStatusCodes.HTTP_409_CONFLICT.value: { 'message': 'CONFLICT' },
    HttpStatusCodes.HTTP_410_GONE.value: { 'message': 'GONE' },
    HttpStatusCodes.HTTP_411_LENGTH_REQUIRED.value: { 'message': 'LENGTH_REQUIRED' },
    HttpStatusCodes.HTTP_412_PRECONDITION_FAILED.value: { 'message': 'PRECONDITION_FAILED' },
    HttpStatusCodes.HTTP_413_REQUEST_ENTITY_TOO_LARGE.value: { 'message': 'REQUEST_ENTITY_TOO_LARGE' },
    HttpStatusCodes.HTTP_414_REQUEST_URI_TOO_LONG.value: { 'message': 'REQUEST_URI_TOO_LONG' },
    HttpStatusCodes.HTTP_415_UNSUPPORTED_MEDIA_TYPE.value: { 'message': 'UNSUPPORTED_MEDIA_TYPE' },
    HttpStatusCodes.HTTP_416_REQUESTED_RANGE_NOT_SATISFIABLE.value: { 'message': 'REQUESTED_RANGE_NOT_SATISFIABLE' },
    HttpStatusCodes.HTTP_417_EXPECTATION_FAILED.value: { 'message': 'EXPECTATION_FAILED' },
    HttpStatusCodes.HTTP_422_UNPROCESSABLE_ENTITY.value: { 'message': 'UNPROCESSABLE_ENTITY' },
    HttpStatusCodes.HTTP_423_LOCKED.value: { 'message': 'LOCKED' },
    HttpStatusCodes.HTTP_424_FAILED_DEPENDENCY.value: { 'message': 'FAILED_DEPENDENCY' },
    HttpStatusCodes.HTTP_426_UPGRADE_REQUIRED.value: { 'message': 'UPGRADE_REQUIRED' },
    HttpStatusCodes.HTTP_428_PRECONDITION_REQUIRED.value: { 'message': 'PRECONDITION_REQUIRED' },
    HttpStatusCodes.HTTP_429_TOO_MANY_REQUESTS.value: { 'message': 'TOO_MANY_REQUESTS' },
    HttpStatusCodes.HTTP_431_REQUEST_HEADER_FIELDS_TOO_LARGE.value: { 'message': 'REQUEST_HEADER_FIELDS_TOO_LARGE' },
    HttpStatusCodes.HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS.value: { 'message': 'UNAVAILABLE_FOR_LEGAL_REASONS' }
}

SERVER_ERRORS_DICT = {
    HttpStatusCodes.HTTP_500_INTERNAL_SERVER_ERROR.value: { 'message': 'INTERNAL_SERVER_ERROR' },
    HttpStatusCodes.HTTP_501_NOT_IMPLEMENTED.value: { 'message': 'NOT_IMPLEMENTED' },
    HttpStatusCodes.HTTP_502_BAD_GATEWAY.value: { 'message': 'BAD_GATEWAY' },
    HttpStatusCodes.HTTP_503_SERVICE_UNAVAILABLE.value: { 'message': 'SERVICE_UNAVAILABLE' },
    HttpStatusCodes.HTTP_504_GATEWAY_TIMEOUT.value: { 'message': 'GATEWAY_TIMEOUT' },
    HttpStatusCodes.HTTP_505_HTTP_VERSION_NOT_SUPPORTED.value: { 'message': 'HTTP_VERSION_NOT_SUPPORTED' },
    HttpStatusCodes.HTTP_506_VARIANT_ALSO_NEGOTIATES.value: { 'message': 'VARIANT_ALSO_NEGOTIATES' },
    HttpStatusCodes.HTTP_507_INSUFFICIENT_STORAGE.value: { 'message': 'INSUFFICIENT_STORAGE' },
    HttpStatusCodes.HTTP_508_LOOP_DETECTED.value: { 'message': 'LOOP_DETECTED' },
    HttpStatusCodes.HTTP_509_BANDWIDTH_LIMIT_EXCEEDED.value: { 'message': 'BANDWIDTH_LIMIT_EXCEEDED' },
    HttpStatusCodes.HTTP_510_NOT_EXTENDED.value: { 'message': 'NOT_EXTENDED' },
    HttpStatusCodes.HTTP_511_NETWORK_AUTHENTICATION_REQUIRED.value: { 'message': 'NETWORK_AUTHENTICATION_REQUIRED' }
}